Repository sopt-makers/sopt-playground-backend, pull requests merged in 2024-10, with the labels that each got.

#487 [Feat] 커피챗 수신 API 문자 발송 기능 추가
  src/main/java/org/sopt/makers/internal/dto/member/CoffeeChatRequest.java
  src/main/java/org/sopt/makers/internal/external/MessageSender.java
  src/main/java/org/sopt/makers/internal/external/MessageSenderFactory.java
  src/main/java/org/sopt/makers/internal/external/email/EmailChatSender.java
  src/main/java/org/sopt/makers/internal/external/email/EmailSender.java
  src/main/java/org/sopt/makers/internal/external/gabia/SmsChatSender.java
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/ChatCategory.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChatHistory.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatHistoryRepository.java
  src/main/java/org/sopt/makers/internal/member/service/MemberRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatCreator.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/EmailHistoryService.java
  src/main/java/org/sopt/makers/internal/service/AuthService.java
Labels: ✨Feature, ♻️ Refactor, 예준🐈, size/L

#497 [Feat] 커피챗 정보 삭제 API
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChat.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatCreator.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
Labels: ✨Feature, 예준🐈, size/M

#495 [Feat] 커피챗 정보 수정 API
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChat.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
Labels: ✨Feature, 예준🐈, size/M

#499 [Feat] 커피챗 공개/비공개 설정 API 추가
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChat.java
  src/main/java/org/sopt/makers/internal/member/dto/request/CoffeeChatOpenRequest.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatUpdater.java
Labels: ✨Feature, 예준🐈, size/M

#494 [Feat] 커피챗 정보 생성 API
  src/main/java/org/sopt/makers/internal/controller/GlobalExceptionHandler.java
  src/main/java/org/sopt/makers/internal/domain/Part.java
  src/main/java/org/sopt/makers/internal/external/email/EmailChatSender.java
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/Career.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/ChatCategory.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChat.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChatSection.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChatTopicType.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/MeetingType.java
  src/main/java/org/sopt/makers/internal/member/dto/request/CoffeeChatDetailsRequest.java
  src/main/java/org/sopt/makers/internal/member/dto/request/CoffeeChatRequest.java
  src/main/java/org/sopt/makers/internal/member/dto/response/CoffeeChatResponse.java
  src/main/java/org/sopt/makers/internal/member/mapper/coffeechat/CoffeeChatResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatCreator.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatModifier.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatUpdater.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/EmailHistoryService.java
  src/main/java/org/sopt/makers/internal/repository/MemberProfileQueryRepository.java
  src/main/java/org/sopt/makers/internal/service/MemberService.java
Labels: ✨Feature, 예준🐈, size/L

#500 Feature/#492 recent coffee chat
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/RecentCoffeeChatResponse.java
  src/main/java/org/sopt/makers/internal/member/mapper/coffeechat/CoffeeChatResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepository.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustom.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/dto/CoffeeChatInfoDto.java
  src/main/java/org/sopt/makers/internal/member/repository/soptactivity/MemberSoptActivityRepository.java
  src/main/java/org/sopt/makers/internal/member/repository/soptactivity/dto/SoptActivityInfoDto.java
  src/main/java/org/sopt/makers/internal/member/service/MemberRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
  src/main/java/org/sopt/makers/internal/service/AuthService.java
  src/main/java/org/sopt/makers/internal/service/InternalApiService.java
  src/main/java/org/sopt/makers/internal/service/MemberService.java
  src/main/java/org/sopt/makers/internal/service/ProjectService.java
Labels: high priority, 승헌✏️, ✨Feature, ♻️ Refactor, size/L

#502 [Feat]: 커피챗 상세조회 API 구현
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/CoffeeChatDetailResponse.java
  src/main/java/org/sopt/makers/internal/member/mapper/coffeechat/CoffeeChatResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/service/MemberRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
Labels: high priority, 승헌✏️, ✨Feature, size/L

#504 [Chore] enum title명 FE와 sync
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/Career.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChatSection.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/MeetingType.java
Labels: ✅ Chore, 예준🐈, size/S

#505 [Chore] deprecate coffeechat in member profile
  src/main/java/org/sopt/makers/internal/domain/Member.java
  src/main/java/org/sopt/makers/internal/dto/member/MemberProfileSaveRequest.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatModifier.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
  src/main/java/org/sopt/makers/internal/service/MemberService.java
Labels: high priority, ✅ Chore, 예준🐈, size/M

#506 [Chore] dev에 slack error alert 추가
  src/main/java/org/sopt/makers/internal/controller/GlobalExceptionHandler.java
Labels: ✅ Chore, 예준🐈, size/XS

#509 [Refactor]: 커피챗 검색 Enum title 필드 적용
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
Labels: high priority, 승헌✏️, ✨Feature, size/S

#511 [Feat]: 커피챗 검색 Career 매핑 추가
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
Labels: high priority, 승헌✏️, ✨Feature, 🛠 Hotfix, size/S

#512 [Chore] member profile response
  src/main/java/org/sopt/makers/internal/dto/member/MemberProfileResponse.java
  src/main/java/org/sopt/makers/internal/mapper/MemberMapper.java
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
Labels: high priority, ✅ Chore, 예준🐈, size/M

#513 [Fix] 커뮤니티 게시글 좋아요 연관관계 updatable 속성 지정
  src/main/java/org/sopt/makers/internal/community/domain/CommunityPostLike.java
Labels: ⛏ Fix, 예준🐈, size/XS

#515 [Fix] MemberProfileUpdateRequest 커피챗 관련 필드 제외
  src/main/java/org/sopt/makers/internal/dto/member/MemberProfileUpdateRequest.java
Labels: high priority, ⛏ Fix, 예준🐈, size/XS

#517 [Fix]: 매직넘버 validation 변경
  src/main/java/org/sopt/makers/internal/common/Constant.java
Labels: size/XS
