Repository sopt-makers/sopt-playground-backend, pull requests merged in 2024-11, with the labels that each got.

#519 [Feat] LMS endpoint 추가
  src/main/java/org/sopt/makers/internal/external/gabia/GabiaService.java
Labels: high priority, ✨Feature, 예준🐈, size/S

#520 chore: CoffeeChat meetingType not null로 제한
  src/main/java/org/sopt/makers/internal/dto/member/MemberProfileUpdateRequest.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChat.java
Labels: ✅ Chore, 예준🐈, size/S

#514 [Chore] 커뮤니티 게시글 리스트 정렬 기준 변경
  src/main/java/org/sopt/makers/internal/repository/community/CommunityQueryRepository.java
Labels: ⛏ Fix, 예준🐈, size/XS

#522 RELEASE 2024/11/03 10:54:30
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java
Labels: size/XS

#523 fix: coffee chat 글자수 제한 변경
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/request/CoffeeChatRequest.java
Labels: high priority, ⛏ Fix, 예준🐈, size/XS

#524 RELEASE 2024/11/03 11:54:30
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/request/CoffeeChatRequest.java
Labels: size/XS

#525 [Chore] apple tester 계정명 변경
  src/main/java/org/sopt/makers/internal/controller/AuthController.java
Labels: high priority, ✅ Chore, 예준🐈, size/XS

#526 RELEASE 2024/11/04 02:09:09
  src/main/java/org/sopt/makers/internal/controller/AuthController.java
Labels: size/XS

#528 [Fix]: 커피챗 상세조회시 section 필드 추가
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/CoffeeChatDetailResponse.java
  src/main/java/org/sopt/makers/internal/member/mapper/coffeechat/CoffeeChatResponseMapper.java
Labels: high priority, 승헌✏️, ⛏ Fix, size/XS

#530 [Feat]: members/me API response에 데이터 추가
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
  src/main/java/org/sopt/makers/internal/member/controller/dto/response/MemberInfoResponse.java
  src/main/java/org/sopt/makers/internal/member/mapper/MemberResponseMapper.java
Labels: high priority, 승헌✏️, ✨Feature, size/M

#533 [Fix]: 최근 진행된 커피챗 중복조회 해결
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
  src/main/java/org/sopt/makers/internal/member/controller/dto/response/MemberInfoResponse.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
Labels: high priority, 승헌✏️, ⛏ Fix, size/M

#537 RELEASE 2024/11/06 21:48:00
  src/main/java/org/sopt/makers/internal/external/gabia/SmsChatSender.java
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/request/CoffeeChatDetailsRequest.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/CoffeeChatDetailResponse.java
  src/main/java/org/sopt/makers/internal/member/controller/dto/response/MemberInfoResponse.java
  src/main/java/org/sopt/makers/internal/member/mapper/MemberResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/mapper/coffeechat/CoffeeChatResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java
  src/main/java/org/sopt/makers/internal/member/service/MemberRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
Labels: release, 승헌✏️, 예준🐈, size/M

#536 [Fix]: 메이커스 이미지 방지
  .gitignore
  src/main/java/org/sopt/makers/internal/community/repository/AnonymousProfileImageRepository.java
  src/main/java/org/sopt/makers/internal/community/service/AnonymousProfileImageService.java
Labels: high priority, 승헌✏️, ⛏ Fix, size/S

#540 [Fix] 멤버 coffee chat 관련 필드 반영
  src/main/java/org/sopt/makers/internal/dto/member/MemberProfileSpecificResponse.java
  src/main/java/org/sopt/makers/internal/mapper/MemberMapper.java
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
Labels: ⛏ Fix, 예준🐈, size/S

#539 Feature/#538 user properties
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
  src/main/java/org/sopt/makers/internal/member/controller/dto/response/MemberPropertiesResponse.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChatStatus.java
  src/main/java/org/sopt/makers/internal/member/mapper/MemberResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatHistoryRepository.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/dto/MemberCoffeeChatPropertyDto.java
  src/main/java/org/sopt/makers/internal/member/util/MemberUtil.java
  src/main/java/org/sopt/makers/internal/service/MemberService.java
Labels: high priority, 승헌✏️, ✨Feature, size/L

#542 [Feat]: 커피챗 커리어 필드 추가
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/Career.java
Labels: high priority, 승헌✏️, ✨Feature, size/XS

#543 [Fix] isCoffeeChatActivate param 추가
  src/main/java/org/sopt/makers/internal/dto/member/MemberProfileSpecificResponse.java
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
Labels: ⛏ Fix, 예준🐈, size/XS

#544 RELEASE 2024/11/09 20:56:00
  .gitignore
  src/main/java/org/sopt/makers/internal/community/repository/AnonymousProfileImageRepository.java
  src/main/java/org/sopt/makers/internal/community/service/AnonymousProfileImageService.java
  src/main/java/org/sopt/makers/internal/dto/member/MemberProfileSpecificResponse.java
  src/main/java/org/sopt/makers/internal/mapper/MemberMapper.java
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
  src/main/java/org/sopt/makers/internal/member/controller/dto/response/MemberPropertiesResponse.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/Career.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChatStatus.java
  src/main/java/org/sopt/makers/internal/member/mapper/MemberResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatHistoryRepository.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/dto/MemberCoffeeChatPropertyDto.java
  src/main/java/org/sopt/makers/internal/member/util/MemberUtil.java
  src/main/java/org/sopt/makers/internal/service/MemberService.java
Labels: size/L

#546 Fix/#545 is coffee chat activate
  src/main/java/org/sopt/makers/internal/domain/Member.java
  src/main/java/org/sopt/makers/internal/repository/MemberRepository.java
Labels: high priority, 승헌✏️, ⛏ Fix, size/S

#547 RELEASE 2024/11/10 20:30:00
  src/main/java/org/sopt/makers/internal/domain/Member.java
  src/main/java/org/sopt/makers/internal/repository/MemberRepository.java
Labels: release, size/S

#549 [Feat] internal api for app
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepositoryCustom.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepositoryCustomImpl.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/controller/InternalOpenApiController.java
  src/main/java/org/sopt/makers/internal/dto/community/InternalCommunityPost.java
  src/main/java/org/sopt/makers/internal/dto/community/PostCategoryDao.java
  src/main/java/org/sopt/makers/internal/dto/internal/InternalMemberProjectResponse.java
  src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java
  src/main/java/org/sopt/makers/internal/mapper/ProjectResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/InternalCoffeeChatMemberResponse.java
  src/main/java/org/sopt/makers/internal/member/mapper/coffeechat/CoffeeChatResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/dto/InternalCoffeeChatMemberDto.java
  src/main/java/org/sopt/makers/internal/member/service/MemberRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
  src/main/java/org/sopt/makers/internal/repository/MemberProfileQueryRepository.java
  src/main/java/org/sopt/makers/internal/repository/ProjectQueryRepository.java
  src/main/java/org/sopt/makers/internal/repository/community/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/repository/community/CommunityQueryRepository.java
  src/main/java/org/sopt/makers/internal/service/MemberService.java
  src/main/java/org/sopt/makers/internal/service/ProjectService.java
Labels: ✨Feature, 예준🐈, size/L

#550 RELEASE 2024/11/13 00:42:00
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepositoryCustom.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepositoryCustomImpl.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/controller/InternalOpenApiController.java
  src/main/java/org/sopt/makers/internal/dto/community/InternalCommunityPost.java
  src/main/java/org/sopt/makers/internal/dto/community/PostCategoryDao.java
  src/main/java/org/sopt/makers/internal/dto/internal/InternalMemberProjectResponse.java
  src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java
  src/main/java/org/sopt/makers/internal/mapper/ProjectResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/InternalCoffeeChatMemberResponse.java
  src/main/java/org/sopt/makers/internal/member/mapper/coffeechat/CoffeeChatResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/dto/InternalCoffeeChatMemberDto.java
  src/main/java/org/sopt/makers/internal/member/service/MemberRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
  src/main/java/org/sopt/makers/internal/repository/MemberProfileQueryRepository.java
  src/main/java/org/sopt/makers/internal/repository/ProjectQueryRepository.java
  src/main/java/org/sopt/makers/internal/repository/community/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/repository/community/CommunityQueryRepository.java
  src/main/java/org/sopt/makers/internal/service/MemberService.java
  src/main/java/org/sopt/makers/internal/service/ProjectService.java
Labels: release, 예준🐈, size/L

#552 [Feat]: 최근 커뮤니티 게시글 조회 필드 추가
  src/main/java/org/sopt/makers/internal/dto/community/InternalCommunityPost.java
  src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java
Labels: high priority, 승헌✏️, ✨Feature, size/XS

#554 RELEASE 2024/11/16 16:09:00
  src/main/java/org/sopt/makers/internal/dto/community/InternalCommunityPost.java
  src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java
Labels: size/XS

#558 [Feat] coffee chat 최신순 정렬 추가
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java
Labels: ✨Feature, 예준🐈, size/XS
