Repository sopt-makers/sopt-playground-backend, pull requests merged in 2025-08, with the labels that each got.

#720 [Feat] 카테고리에 모임글 불러오기 API 연결
  src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
  src/main/java/org/sopt/makers/internal/community/dto/response/PostResponse.java
  src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/external/makers/CrewMeeting.java
  src/main/java/org/sopt/makers/internal/external/makers/CrewMeetingListResponse.java
  src/main/java/org/sopt/makers/internal/external/makers/CrewPost.java
  src/main/java/org/sopt/makers/internal/external/makers/CrewPostListResponse.java
  src/main/java/org/sopt/makers/internal/external/makers/MakersCrewClient.java
Labels: ✨Feature, size/L, 정교🥑

#722 [Feat] 토큰에서 prefix 제거하는 로직 구현
  src/main/java/org/sopt/makers/internal/auth/jwtFilter/JwtAuthenticationFilter.java
Labels: ✨Feature, size/S

#729 [Feat] map 변환 시 duplicate 오류 일어나지 않도록 수정
  src/main/java/org/sopt/makers/internal/coffeechat/service/CoffeeChatService.java
  src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
  src/main/java/org/sopt/makers/internal/wordchaingame/controller/WordChainGameController.java
  src/main/java/org/sopt/makers/internal/wordchaingame/service/WordChainGameService.java
Labels: ⛏ Fix, size/M

#741 [Fix] 플그 기본 유저 프로필 생성 api 추가
  src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java
  src/main/java/org/sopt/makers/internal/internal/dto/CreateDefaultUserProfileRequest.java
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
  src/main/java/org/sopt/makers/internal/member/domain/Member.java
  src/main/java/org/sopt/makers/internal/member/dto/response/MemberProfileResponse.java
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
  src/main/java/org/sopt/makers/internal/project/mapper/ProjectResponseMapper.java
Labels: size/M

#743 [Feat] 공홈이 사용하는 프로젝트 조회 api 인증 구조 삭제
  src/main/java/org/sopt/makers/internal/auth/jwtFilter/JwtAuthenticationFilter.java
  src/main/java/org/sopt/makers/internal/auth/security/config/SecurityConfig.java
  src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java
Labels: ⛏ Fix, size/S

#745 [Fix] 프로필 조회 에러 핸들링 및 base url 수정
  src/main/java/org/sopt/makers/internal/common/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java
Labels: size/M

#746 [Fix] 기본 프로필 생성 중복 유저 에러 핸들링 수정
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
Labels: size/XS

#749 [Fix] 커피챗 중복정보 응답 수정 및 memberProfile의 activities 정보 누락 수정
  src/main/java/org/sopt/makers/internal/coffeechat/service/CoffeeChatService.java
  src/main/java/org/sopt/makers/internal/member/mapper/MemberMapper.java
Labels: ⛏ Fix, size/M, 정교🥑

#751 [Fix] MemberPart 요청형식 수정
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
Labels: ⛏ Fix, size/S, 정교🥑

#752 RELEASE 2025-08-31 22:27:00
  src/main/java/org/sopt/makers/internal/coffeechat/service/CoffeeChatService.java
  src/main/java/org/sopt/makers/internal/member/mapper/MemberMapper.java
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
Labels: release, size/M, 정교🥑

#753 RELEASE 2025-08-31 22:59:00
  src/main/java/org/sopt/makers/internal/coffeechat/service/CoffeeChatService.java
Labels: release, size/XS, 정교🥑

#757 [Fix] isBlinder 여부와 상관없이 isMine이 true면 phoneNumber를 보여주도록 수정
  src/main/java/org/sopt/makers/internal/member/dto/response/MemberProfileSpecificResponse.java
Labels: ⛏ Fix, size/XS, 정교🥑
