Repository sopt-makers/sopt-playground-backend, pull requests merged in 2025-09, with the labels that each got.

#763 RELEASE 2025-09-7 21:27:00
  src/main/java/org/sopt/makers/internal/auth/jwt/code/JwkFailure.java
  src/main/java/org/sopt/makers/internal/auth/jwt/code/JwtFailure.java
  src/main/java/org/sopt/makers/internal/auth/jwt/service/JwkProvider.java
  src/main/java/org/sopt/makers/internal/auth/jwt/service/JwtAuthenticationService.java
  src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java
Labels: size/M

#770 [Fix] 멤버 필터링 조회 및 페이지네이션 처리 로직 수정
  src/main/java/org/sopt/makers/internal/external/platform/GetPlatformUserBatchRequest.java
  src/main/java/org/sopt/makers/internal/external/platform/PlatformClient.java
  src/main/java/org/sopt/makers/internal/external/platform/PlatformService.java
  src/main/java/org/sopt/makers/internal/member/repository/MemberProfileQueryRepository.java
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
Labels: ⛏ Fix, size/L, 찬기🔓

#772 [Refactor] 타임캡솝 37기 업데이트 내용 반영
  src/main/java/org/sopt/makers/internal/common/Constant.java
  src/main/java/org/sopt/makers/internal/external/GoogleSheetsService.java
  src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionService.java
  src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionServiceUtil.java
Labels: size/M

#773 [Feat] 37기 인증 중앙화 & 타임캡솝 & 오류 수정사항들 Prod 반영
  src/main/java/org/sopt/makers/internal/auth/AuthConfig.java
  src/main/java/org/sopt/makers/internal/common/Constant.java
  src/main/java/org/sopt/makers/internal/external/GoogleSheetsService.java
  src/main/java/org/sopt/makers/internal/external/platform/GetPlatformUserBatchRequest.java
  src/main/java/org/sopt/makers/internal/external/platform/PlatformClient.java
  src/main/java/org/sopt/makers/internal/external/platform/PlatformService.java
  src/main/java/org/sopt/makers/internal/internal/InternalApiService.java
  src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java
  src/main/java/org/sopt/makers/internal/internal/auth/ApiKeyValidator.java
  src/main/java/org/sopt/makers/internal/internal/dto/InternalRecommendMemberListRequest.java
  src/main/java/org/sopt/makers/internal/member/repository/MemberProfileQueryRepository.java
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
  src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionService.java
  src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionServiceUtil.java
  src/test/resources/application.yml
Labels: size/XXL

#774 [Fix] 멤버 리스트 조회 cursor 파라미터 offset 기반으로 로직 처리
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
Labels: size/S

#775 [Fix] 멤버 리스트 조회 페이지네이션 오류 수정 Prod 배포
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
Labels: size/S

#776 [Fix] 멤버 ordering 복구
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
Labels: size/M

#777 [Fix] 삭제된 멤버 정렬 기준 복구
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
Labels: size/M

#778 [Fix] 멤버 리스트 필터링 조회 오류 수정
  src/main/java/org/sopt/makers/internal/external/platform/PlatformService.java
  src/main/java/org/sopt/makers/internal/external/platform/SoptActivity.java
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
Labels: size/L

#784 [Fix] 37기 QA 멤버 이슈 수정
  src/main/java/org/sopt/makers/internal/external/platform/PlatformService.java
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
Labels: size/S
