Repository sopt-makers/sopt-playground-backend, pull requests merged in 2025-01, with the labels that each got.

#568 chore: update directory name
  .github/workflows/cd-to-dev.yml
  .github/workflows/cd-to-prod.yml
  docker-compose.yml
  scripts/deploy.sh
  scripts/nginx_reload.sh
Labels: size/M

#573 [Fix]: 커피챗 자기소개 필드 옵셔널로 변경
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/request/CoffeeChatDetailsRequest.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChat.java
Labels: high priority, 승헌✏️, ⛏ Fix, size/XS

#574 fix: deploy path 변경
  scripts/deploy.sh
Labels: size/XS

#571 [Refactor]: 커뮤니티 게시글 조회수 비관적 락 적용
  src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
  src/main/java/org/sopt/makers/internal/community/domain/CommunityPost.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/config/BucketConfig.java
  src/main/java/org/sopt/makers/internal/repository/PostRepository.java
Labels: high priority, 승헌✏️, ⛏ Fix, size/M

#579 Feature/#578 coffee chat
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/request/CoffeeChatReviewRequest.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/CoffeeChatHistoryTitleResponse.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/CoffeeChatReviewResponse.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChatReview.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatHistoryRepository.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustom.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatReviewRepository.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatModifier.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
Labels: high priority, 승헌✏️, ✨Feature, size/L

#582 [Feat] 마이 솝트 리포트 마이 플그 파트 데이터 조회 API
  build.gradle
  src/main/java/org/sopt/makers/internal/common/Constant.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostLikeRepository.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/config/cache/CacheConfig.java
  src/main/java/org/sopt/makers/internal/config/cache/CacheConstant.java
  src/main/java/org/sopt/makers/internal/config/cache/CacheType.java
  src/main/java/org/sopt/makers/internal/dto/amplitude/AmplitudeEventResponse.java
  src/main/java/org/sopt/makers/internal/dto/amplitude/AmplitudeUserResponse.java
  src/main/java/org/sopt/makers/internal/external/amplitude/AmplitudeClient.java
  src/main/java/org/sopt/makers/internal/external/amplitude/AmplitudeService.java
  src/main/java/org/sopt/makers/internal/external/amplitude/EventData.java
  src/main/java/org/sopt/makers/internal/report/controller/SoptReportStatsController.java
  src/main/java/org/sopt/makers/internal/report/domain/PlaygroundType.java
  src/main/java/org/sopt/makers/internal/report/dto/PlayGroundTypeStatsDto.java
  src/main/java/org/sopt/makers/internal/report/dto/response/MySoptReportStatsResponse.java
  src/main/java/org/sopt/makers/internal/report/service/SoptReportStatsService.java
  src/main/java/org/sopt/makers/internal/repository/WordChainGameQueryRepository.java
  src/main/java/org/sopt/makers/internal/repository/WordRepository.java
  src/main/java/org/sopt/makers/internal/repository/community/CommunityCommentRepository.java
Labels: ✨Feature, 예준🐈, size/XL

#580 [Feat] 마이 솝트 리포트 공통 데이터 조회 API
  build.gradle
  src/main/java/org/sopt/makers/internal/common/Constant.java
  src/main/java/org/sopt/makers/internal/common/JsonDataSerializer.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostLikeRepository.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/config/cache/CacheConfig.java
  src/main/java/org/sopt/makers/internal/config/cache/CacheConstant.java
  src/main/java/org/sopt/makers/internal/config/cache/CacheType.java
  src/main/java/org/sopt/makers/internal/dto/amplitude/AmplitudeEventResponse.java
  src/main/java/org/sopt/makers/internal/dto/amplitude/AmplitudeUserResponse.java
  src/main/java/org/sopt/makers/internal/external/amplitude/AmplitudeClient.java
  src/main/java/org/sopt/makers/internal/external/amplitude/AmplitudeService.java
  src/main/java/org/sopt/makers/internal/external/amplitude/EventData.java
  src/main/java/org/sopt/makers/internal/report/controller/SoptReportStatsController.java
  src/main/java/org/sopt/makers/internal/report/domain/PlaygroundType.java
  src/main/java/org/sopt/makers/internal/report/domain/SoptReportCategory.java
  src/main/java/org/sopt/makers/internal/report/domain/SoptReportStats.java
  src/main/java/org/sopt/makers/internal/report/dto/PlayGroundTypeStatsDto.java
  src/main/java/org/sopt/makers/internal/report/dto/response/MySoptReportStatsResponse.java
  src/main/java/org/sopt/makers/internal/report/repository/SoptReportStatsRepository.java
  src/main/java/org/sopt/makers/internal/report/service/SoptReportStatsService.java
  src/main/java/org/sopt/makers/internal/repository/WordChainGameQueryRepository.java
  src/main/java/org/sopt/makers/internal/repository/WordRepository.java
  src/main/java/org/sopt/makers/internal/repository/community/CommunityCommentRepository.java
  src/test/resources/application.yml
Labels: ✨Feature, 예준🐈, size/XL

#583 [Feat] 마이 솝트 리포트 크루 데이터 추가
  src/main/java/org/sopt/makers/internal/external/MakersCrewClient.java
  src/main/java/org/sopt/makers/internal/external/amplitude/AmplitudeService.java
  src/main/java/org/sopt/makers/internal/external/amplitude/EventData.java
  src/main/java/org/sopt/makers/internal/report/dto/CrewFastestJoinedGroupResponse.java
  src/main/java/org/sopt/makers/internal/report/service/SoptReportStatsService.java
  src/test/resources/application.yml
Labels: ✨Feature, 예준🐈, size/M

#584 RELEASE 2025-02-01 03:07:10
  build.gradle
  src/main/java/org/sopt/makers/internal/common/Constant.java
  src/main/java/org/sopt/makers/internal/common/JsonDataSerializer.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostLikeRepository.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/config/cache/CacheConfig.java
  src/main/java/org/sopt/makers/internal/config/cache/CacheConstant.java
  src/main/java/org/sopt/makers/internal/config/cache/CacheType.java
  src/main/java/org/sopt/makers/internal/dto/amplitude/AmplitudeEventResponse.java
  src/main/java/org/sopt/makers/internal/dto/amplitude/AmplitudeUserResponse.java
  src/main/java/org/sopt/makers/internal/external/MakersCrewClient.java
  src/main/java/org/sopt/makers/internal/external/amplitude/AmplitudeClient.java
  src/main/java/org/sopt/makers/internal/external/amplitude/AmplitudeService.java
  src/main/java/org/sopt/makers/internal/external/amplitude/EventData.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/CoffeeChatController.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/request/CoffeeChatReviewRequest.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/CoffeeChatHistoryTitleResponse.java
  src/main/java/org/sopt/makers/internal/member/controller/coffeechat/dto/response/CoffeeChatReviewResponse.java
  src/main/java/org/sopt/makers/internal/member/domain/coffeechat/CoffeeChatReview.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatHistoryRepository.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustom.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatRepositoryCustomImpl.java
  src/main/java/org/sopt/makers/internal/member/repository/coffeechat/CoffeeChatReviewRepository.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatModifier.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatRetriever.java
  src/main/java/org/sopt/makers/internal/member/service/coffeechat/CoffeeChatService.java
  src/main/java/org/sopt/makers/internal/report/controller/SoptReportStatsController.java
  src/main/java/org/sopt/makers/internal/report/domain/PlaygroundType.java
  src/main/java/org/sopt/makers/internal/report/domain/SoptReportCategory.java
  src/main/java/org/sopt/makers/internal/report/domain/SoptReportStats.java
  src/main/java/org/sopt/makers/internal/report/dto/CrewFastestJoinedGroupResponse.java
  src/main/java/org/sopt/makers/internal/report/dto/PlayGroundTypeStatsDto.java
  src/main/java/org/sopt/makers/internal/report/dto/response/MySoptReportStatsResponse.java
  src/main/java/org/sopt/makers/internal/report/repository/SoptReportStatsRepository.java
  src/main/java/org/sopt/makers/internal/report/service/SoptReportStatsService.java
  src/main/java/org/sopt/makers/internal/repository/WordChainGameQueryRepository.java
  src/main/java/org/sopt/makers/internal/repository/WordRepository.java
  src/main/java/org/sopt/makers/internal/repository/community/CommunityCommentRepository.java
  src/test/resources/application.yml
Labels: release, size/XXL
