Repository sopt-makers/sopt-playground-backend, pull requests merged in 2025-03, with the labels that each got.

#590 Refactor/#589 view count
  src/main/java/org/sopt/makers/internal/community/domain/CommunityPost.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostModifier.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/repository/PostRepository.java
Labels: size/M

#592 [Chore]: 현재 기수 36기로 업데이트
  src/main/java/org/sopt/makers/internal/common/Constant.java
Labels: ✅ Chore, size/XS, 주민🥭

#596 [Chore] 타임캡솝 조회 및 삭제 기능 수정 및 추가
  src/main/java/org/sopt/makers/internal/resolution/controller/UserResolutionController.java
  src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionService.java
Labels: ✅ Chore, size/M, 정교🥑

#594 [Chore] 타임캡솝 태그 유형 수정
  src/main/java/org/sopt/makers/internal/resolution/controller/UserResolutionController.java
  src/main/java/org/sopt/makers/internal/resolution/domain/ResolutionTag.java
  src/main/java/org/sopt/makers/internal/resolution/domain/UserResolution.java
  src/main/java/org/sopt/makers/internal/resolution/dto/request/ResolutionSaveRequest.java
  src/main/java/org/sopt/makers/internal/resolution/dto/response/ResolutionResponse.java
  src/main/java/org/sopt/makers/internal/resolution/mapper/UserResolutionResponseMapper.java
  src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionService.java
Labels: ✅ Chore, size/L, 주민🥭

#597 [Feat] 구글 스프레드 시트 연동 로깅
  .gitignore
  build.gradle
  src/main/java/org/sopt/makers/internal/common/GoogleSheetsService.java
  src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionService.java
  src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionServiceUtil.java
  src/test/resources/application.yml
Labels: ✨Feature, size/L, 주민🥭

#598 RELEASE 2025-03-29 00:37:30
  .gitignore
  build.gradle
  src/main/java/org/sopt/makers/internal/common/Constant.java
  src/main/java/org/sopt/makers/internal/common/GoogleSheetsService.java
  src/main/java/org/sopt/makers/internal/community/domain/CommunityPost.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostModifier.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/repository/PostRepository.java
  src/main/java/org/sopt/makers/internal/resolution/controller/UserResolutionController.java
  src/main/java/org/sopt/makers/internal/resolution/domain/ResolutionTag.java
  src/main/java/org/sopt/makers/internal/resolution/domain/UserResolution.java
  src/main/java/org/sopt/makers/internal/resolution/dto/request/ResolutionSaveRequest.java
  src/main/java/org/sopt/makers/internal/resolution/dto/response/ResolutionResponse.java
  src/main/java/org/sopt/makers/internal/resolution/mapper/UserResolutionResponseMapper.java
  src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionService.java
  src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionServiceUtil.java
  src/test/resources/application.yml
Labels: release, size/L
