Repository sopt-makers/sopt-playground-backend, pull requests merged in 2025-05, with the labels that each got.

#618 [Chore]: 정렬 순서 생성 날짜 내림차순으로 변경
  src/main/java/org/sopt/makers/internal/repository/community/CommunityQueryRepository.java
Labels: ✅ Chore, size/XS, 주민🥭

#619 RELEASE 2025-05-01 14:52:00
  src/main/java/org/sopt/makers/internal/repository/community/CommunityQueryRepository.java
Labels: release, size/XS, 주민🥭

#624 [Fix]: Subject 필드를 리스트 형태로 받아오도록 수정
  src/main/java/org/sopt/makers/internal/community/dto/response/ReviewCountResponse.java
Labels: ⛏ Fix, size/XS, 정교🥑

#626 [Fix] 자신이 작성한 글에 익명 댓글 작성되도록 수정
  src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
  src/main/java/org/sopt/makers/internal/community/repository/post/CommunityPostLikeRepository.java
  src/main/java/org/sopt/makers/internal/community/repository/post/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/community/repository/post/CommunityPostRepositoryCustom.java
  src/main/java/org/sopt/makers/internal/community/repository/post/CommunityPostRepositoryCustomImpl.java
  src/main/java/org/sopt/makers/internal/community/repository/post/DeletedCommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityCommentService.java
  src/main/java/org/sopt/makers/internal/community/service/comment/CommunityCommentModifier.java
  src/main/java/org/sopt/makers/internal/community/service/comment/CommunityCommentsRetriever.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostModifier.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostRetriever.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
  src/main/java/org/sopt/makers/internal/report/service/SoptReportStatsService.java
  src/main/java/org/sopt/makers/internal/scheduler/PushNotificationScheduler.java
  src/test/java/org/sopt/makers/internal/service/community/CommunityServiceUnitTest.java
Labels: ⛏ Fix, size/L, 주민🥭

#628 [Feat] 인기글 3개 조회 API 구현
  src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
  src/main/java/org/sopt/makers/internal/community/dto/MemberVo.java
  src/main/java/org/sopt/makers/internal/community/dto/response/PopularPostResponse.java
  src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityQueryRepository.java
  src/main/java/org/sopt/makers/internal/community/repository/post/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
Labels: ✨Feature, size/M, 주민🥭

#635 [Refac] 인기글 조회 API 요구사항 변경 및 조회 속도 향상
  src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
  src/main/java/org/sopt/makers/internal/community/dto/MemberVo.java
  src/main/java/org/sopt/makers/internal/community/dto/response/PopularPostResponse.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityQueryRepository.java
  src/main/java/org/sopt/makers/internal/community/repository/post/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/member/domain/Member.java
  src/main/java/org/sopt/makers/internal/member/dto/response/MemberNameAndProfileImageResponse.java
Labels: ♻️ Refactor, size/M, 주민🥭

#643 [HotFix] 솝티클 스크랩 이슈 해결
  src/main/java/org/sopt/makers/internal/external/makers/OfficialHomeClient.java
Labels: ⛏ Fix, size/XS, 주민🥭

#639 [Feat] 익명 댓글 5개 제한 해제에 따른 코드 변경
  src/main/java/org/sopt/makers/internal/coffeechat/service/CoffeeChatRetriever.java
  src/main/java/org/sopt/makers/internal/coffeechat/service/CoffeeChatService.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityCommentService.java
  src/main/java/org/sopt/makers/internal/community/service/anonymous/AnonymousPostProfileService.java
  src/main/java/org/sopt/makers/internal/community/service/anonymous/AnonymousProfileImageRetriever.java
  src/test/java/org/sopt/makers/internal/service/community/anonymous/AnonymousPostProfileServiceTest.java
  src/test/java/org/sopt/makers/internal/service/community/anonymous/AnonymousProfileImageRetrieverTest.java
Labels: ✨Feature, ⛏ Fix, size/M, 주민🥭

#641 [Fix] 인기글 글 조회 시 익명글은 익명 프로필 처리하도록 수정
  src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
  src/main/java/org/sopt/makers/internal/community/dto/response/PopularPostResponse.java
  src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityQueryRepository.java
  src/main/java/org/sopt/makers/internal/community/repository/anonymous/AnonymousPostProfileRepository.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
Labels: ⛏ Fix, size/L, 주민🥭

#651 [Refactor] 카테고리 반환해 주는 API 정렬 순서 변경
  src/main/java/org/sopt/makers/internal/community/controller/CommunityCategoryController.java
  src/main/java/org/sopt/makers/internal/community/domain/category/Category.java
  src/main/java/org/sopt/makers/internal/community/dto/response/CommunityCategoryResponse.java
  src/main/java/org/sopt/makers/internal/community/service/category/CategoryService.java
  src/test/java/org/sopt/makers/internal/service/community/category/CategoryServiceUnitTest.java
Labels: ♻️ Refactor, size/S, 정교🥑

#655 RELEASE 2025-05-31 24:27:00
  src/main/java/org/sopt/makers/internal/community/repository/CommunityQueryRepository.java
Labels: release, 🛠 Hotfix, size/XS, 정교🥑

#656 RELEASE 2025-05-31 1:47:00
  src/main/java/org/sopt/makers/internal/community/repository/CommunityQueryRepository.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
Labels: release, 🛠 Hotfix, size/M, 정교🥑
