Repository sopt-makers/sopt-playground-backend, pull requests merged in 2025-06, with the labels that each got.

#662 [Feat] 투표 관련 파일 추가
  src/main/java/org/sopt/makers/internal/community/domain/CommunityPost.java
  src/main/java/org/sopt/makers/internal/member/domain/Member.java
  src/main/java/org/sopt/makers/internal/vote/VoteQueryRepository.java
  src/main/java/org/sopt/makers/internal/vote/VoteService.java
  src/main/java/org/sopt/makers/internal/vote/domain/Vote.java
  src/main/java/org/sopt/makers/internal/vote/domain/VoteOption.java
  src/main/java/org/sopt/makers/internal/vote/domain/VoteSelection.java
Labels: ✨Feature, size/L

#664 [Feat] 투표 생성 기능 구현
  src/main/java/org/sopt/makers/internal/community/dto/request/PostSaveRequest.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/vote/VoteService.java
  src/main/java/org/sopt/makers/internal/vote/domain/Vote.java
  src/main/java/org/sopt/makers/internal/vote/domain/VoteOption.java
  src/main/java/org/sopt/makers/internal/vote/dto/request/VoteRequest.java
  src/main/java/org/sopt/makers/internal/vote/repository/VoteQueryRepository.java
  src/main/java/org/sopt/makers/internal/vote/repository/VoteRepository.java
  src/main/java/org/sopt/makers/internal/vote/service/VoteService.java
  src/test/java/org/sopt/makers/internal/service/community/CommunityServiceUnitTest.java
Labels: ✨Feature, size/L, 정교🥑

#666 [Feat] 투표 선택 기능 구현
  src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
  src/main/java/org/sopt/makers/internal/vote/domain/Vote.java
  src/main/java/org/sopt/makers/internal/vote/domain/VoteOption.java
  src/main/java/org/sopt/makers/internal/vote/domain/VoteSelection.java
  src/main/java/org/sopt/makers/internal/vote/dto/request/VoteSelectionRequest.java
  src/main/java/org/sopt/makers/internal/vote/repository/VoteOptionRepository.java
  src/main/java/org/sopt/makers/internal/vote/repository/VoteRepository.java
  src/main/java/org/sopt/makers/internal/vote/repository/VoteSelectionRepository.java
  src/main/java/org/sopt/makers/internal/vote/service/VoteService.java
  src/test/java/org/sopt/makers/internal/vote/service/VoteServiceTest.java
Labels: ✨Feature, size/L, 정교🥑

#668 [chore] PATCH > POST API로 수정
  src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
Labels: ✅ Chore, size/XS, 정교🥑

#676 [chore] post 응답에 vote 객체 함께 반한하도록 수정
  src/main/java/org/sopt/makers/internal/community/dto/response/PostSaveResponse.java
  src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
Labels: ✅ Chore, size/S, 정교🥑

#678 [chore] 원본 불변리스트가 아닌 복사한 새로운 가변 리스트를 사용하도록 수정
  src/main/java/org/sopt/makers/internal/vote/service/VoteService.java
Labels: ⛏ Fix, ✅ Chore, size/S, 정교🥑
