Repository sopt-makers/sopt-playground-backend, pull requests merged in 2025-04, with the labels that each got.

#600 [Refactor] 커뮤니티에서 솝티클을 관리할 수 있도록 조회 응답값 수정
  src/main/java/org/sopt/makers/internal/community/domain/CommunityPost.java
  src/main/java/org/sopt/makers/internal/dto/community/CommunityPostVo.java
  src/main/java/org/sopt/makers/internal/dto/community/PostResponse.java
  src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java
Labels: ♻️ Refactor, size/S, 정교🥑

#602 [Chore] 커뮤니티 카테고리 목록 조회 정렬 수정
  src/main/java/org/sopt/makers/internal/community/service/category/CategoryService.java
Labels: ✅ Chore, size/XS, 주민🥭

#604 [Refac] 불필요한 Column 어노테이션 삭제
  src/main/java/org/sopt/makers/internal/community/domain/CommunityPost.java
  src/main/java/org/sopt/makers/internal/dto/community/CommunityPostVo.java
  src/main/java/org/sopt/makers/internal/dto/community/PostResponse.java
  src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java
Labels: ✅ Chore, size/S, 정교🥑

#606 [Feat] 커뮤니티에 솝티클 생성하도록 로직 수정
  src/main/java/org/sopt/makers/internal/community/controller/dto/request/PostSaveRequest.java
  src/main/java/org/sopt/makers/internal/community/controller/dto/response/SopticleScrapedResponse.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostModifier.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/community/service/SopticleService.java
  src/main/java/org/sopt/makers/internal/controller/GlobalExceptionHandler.java
  src/main/java/org/sopt/makers/internal/controller/SopticleController.java
  src/main/java/org/sopt/makers/internal/domain/Part.java
  src/main/java/org/sopt/makers/internal/domain/Sopticle.java
  src/main/java/org/sopt/makers/internal/domain/SopticleWriter.java
  src/main/java/org/sopt/makers/internal/dto/sopticle/SopticleDao.java
  src/main/java/org/sopt/makers/internal/dto/sopticle/SopticleOfficialResponse.java
  src/main/java/org/sopt/makers/internal/dto/sopticle/SopticleSaveRequest.java
  src/main/java/org/sopt/makers/internal/dto/sopticle/SopticleVo.java
  src/main/java/org/sopt/makers/internal/external/OfficialHomeClient.java
  src/main/java/org/sopt/makers/internal/member/repository/soptactivity/MemberSoptActivityRepository.java
  src/main/java/org/sopt/makers/internal/repository/SopticleQueryRepository.java
  src/main/java/org/sopt/makers/internal/repository/SopticleRepository.java
  src/main/java/org/sopt/makers/internal/repository/SopticleWriterRepository.java
  src/main/java/org/sopt/makers/internal/service/SopticleService.java
  src/test/java/org/sopt/makers/internal/service/community/CommunityServiceUnitTest.java
Labels: ✨Feature, size/L, 주민🥭

#608 [Fix] 공홈 API 요청 시 part 값 변환 로직 삭제
  src/main/java/org/sopt/makers/internal/community/service/SopticleService.java
  src/main/java/org/sopt/makers/internal/domain/Part.java
Labels: size/S

#614 [Feat] userProperty에 유저별 솝티클 업로드 수 및 활동후기 업로드 수 추가
  src/main/java/org/sopt/makers/internal/community/controller/dto/response/ReviewCountResponse.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/community/service/ReviewService.java
  src/main/java/org/sopt/makers/internal/external/OfficialHomeClient.java
  src/main/java/org/sopt/makers/internal/member/controller/dto/response/MemberPropertiesResponse.java
  src/main/java/org/sopt/makers/internal/member/mapper/MemberResponseMapper.java
  src/main/java/org/sopt/makers/internal/service/MemberService.java
Labels: ✨Feature, size/L, 정교🥑

#613 [Chore] 커뮤니티 글 생성/수정 dto에 link 추가
  src/main/java/org/sopt/makers/internal/community/controller/dto/request/PostSaveRequest.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostModifier.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/dto/community/PostUpdateRequest.java
Labels: ✅ Chore, size/S, 주민🥭

#615 RELEASE 2025-04-30 22:41:00
  src/main/java/org/sopt/makers/internal/community/controller/dto/request/PostSaveRequest.java
  src/main/java/org/sopt/makers/internal/community/controller/dto/response/ReviewCountResponse.java
  src/main/java/org/sopt/makers/internal/community/controller/dto/response/SopticleScrapedResponse.java
  src/main/java/org/sopt/makers/internal/community/domain/CommunityPost.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostModifier.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostRetriever.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityPostServiceUtil.java
  src/main/java/org/sopt/makers/internal/community/service/ReviewService.java
  src/main/java/org/sopt/makers/internal/community/service/SopticleScrapedService.java
  src/main/java/org/sopt/makers/internal/community/service/category/CategoryRetriever.java
  src/main/java/org/sopt/makers/internal/community/service/category/CategoryService.java
  src/main/java/org/sopt/makers/internal/controller/GlobalExceptionHandler.java
  src/main/java/org/sopt/makers/internal/controller/MakersMemberController.java
  src/main/java/org/sopt/makers/internal/controller/SopticleController.java
  src/main/java/org/sopt/makers/internal/domain/Sopticle.java
  src/main/java/org/sopt/makers/internal/domain/SopticleWriter.java
  src/main/java/org/sopt/makers/internal/dto/community/CommunityPostVo.java
  src/main/java/org/sopt/makers/internal/dto/community/PostResponse.java
  src/main/java/org/sopt/makers/internal/dto/community/PostUpdateRequest.java
  src/main/java/org/sopt/makers/internal/dto/sopticle/SopticleDao.java
  src/main/java/org/sopt/makers/internal/dto/sopticle/SopticleOfficialResponse.java
  src/main/java/org/sopt/makers/internal/dto/sopticle/SopticleSaveRequest.java
  src/main/java/org/sopt/makers/internal/dto/sopticle/SopticleVo.java
  src/main/java/org/sopt/makers/internal/external/OfficialHomeClient.java
  src/main/java/org/sopt/makers/internal/mapper/CommunityResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/controller/dto/response/MemberPropertiesResponse.java
  src/main/java/org/sopt/makers/internal/member/mapper/MemberResponseMapper.java
  src/main/java/org/sopt/makers/internal/member/repository/soptactivity/MemberSoptActivityRepository.java
  src/main/java/org/sopt/makers/internal/member/service/MemberRetriever.java
  src/main/java/org/sopt/makers/internal/repository/SopticleQueryRepository.java
  src/main/java/org/sopt/makers/internal/repository/SopticleRepository.java
  src/main/java/org/sopt/makers/internal/repository/SopticleWriterRepository.java
  src/main/java/org/sopt/makers/internal/review/service/ActivityReviewService.java
  src/main/java/org/sopt/makers/internal/service/MemberService.java
  src/main/java/org/sopt/makers/internal/service/SopticleService.java
  src/main/java/org/sopt/makers/internal/service/member/MemberServiceUtil.java
  src/test/java/org/sopt/makers/internal/service/community/CommunityServiceUnitTest.java
Labels: release, size/XL, 정교🥑
