Repository sopt-makers/sopt-playground-backend, pull requests merged in 2025-07, with the labels that each got.

#680 [chore] 투표 선택 시 현재 투표상황을 반환하도록 변경
  src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
  src/main/java/org/sopt/makers/internal/community/dto/response/PostSaveResponse.java
  src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/vote/service/VoteService.java
Labels: ✅ Chore, size/S, 정교🥑

#683 [Feat] 언급 푸시 알람 연동
  src/main/java/org/sopt/makers/internal/common/util/MentionCleaner.java
  src/main/java/org/sopt/makers/internal/community/dto/request/CommentSaveRequest.java
  src/main/java/org/sopt/makers/internal/community/dto/request/MentionRequest.java
  src/main/java/org/sopt/makers/internal/community/dto/request/PostSaveRequest.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityCommentService.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/external/pushNotification/PushNotificationService.java
  src/main/java/org/sopt/makers/internal/scheduler/PushNotificationScheduler.java
Labels: ✨Feature, size/L

#684 [Refactor] 홈 질문 최근글 불러오기 api 모든 카테고리 최근글 불러오기로 수정
  src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
  src/main/java/org/sopt/makers/internal/community/dto/response/RecentPostResponse.java
  src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
  src/main/java/org/sopt/makers/internal/community/repository/post/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
  src/test/java/org/sopt/makers/internal/community/service/post/CommunityPostServiceTest.java
Labels: ♻️ Refactor, size/L, 정교🥑

#689 [Refactor] 기존 멤버 검색 api 리팩토링(개수 리밋, 보여주는 순서, 코드 최적화)
  src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
  src/main/java/org/sopt/makers/internal/community/service/category/CategoryRetriever.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
  src/main/java/org/sopt/makers/internal/member/repository/MemberProfileQueryRepository.java
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
  src/test/java/org/sopt/makers/internal/community/service/post/CommunityPostServiceTest.java
  src/test/java/org/sopt/makers/internal/service/community/category/CategoryServiceUnitTest.java
Labels: ♻️ Refactor, size/L, 정교🥑

#692 RELEASE 2025-07-07 10:45:00
  src/main/java/org/sopt/makers/internal/common/util/InfiniteScrollUtil.java
  src/main/java/org/sopt/makers/internal/common/util/MentionCleaner.java
  src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
  src/main/java/org/sopt/makers/internal/community/domain/CommunityPost.java
  src/main/java/org/sopt/makers/internal/community/dto/CategoryPostMemberDao.java
  src/main/java/org/sopt/makers/internal/community/dto/CommunityPostVo.java
  src/main/java/org/sopt/makers/internal/community/dto/request/CommentSaveRequest.java
  src/main/java/org/sopt/makers/internal/community/dto/request/MentionRequest.java
  src/main/java/org/sopt/makers/internal/community/dto/request/PostSaveRequest.java
  src/main/java/org/sopt/makers/internal/community/dto/response/PostResponse.java
  src/main/java/org/sopt/makers/internal/community/dto/response/PostSaveResponse.java
  src/main/java/org/sopt/makers/internal/community/dto/response/RecentPostResponse.java
  src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
  src/main/java/org/sopt/makers/internal/community/repository/post/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityCommentService.java
  src/main/java/org/sopt/makers/internal/community/service/category/CategoryRetriever.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/external/pushNotification/PushNotificationService.java
  src/main/java/org/sopt/makers/internal/member/controller/MemberController.java
  src/main/java/org/sopt/makers/internal/member/domain/Member.java
  src/main/java/org/sopt/makers/internal/member/repository/MemberProfileQueryRepository.java
  src/main/java/org/sopt/makers/internal/member/service/MemberService.java
  src/main/java/org/sopt/makers/internal/scheduler/PushNotificationScheduler.java
  src/main/java/org/sopt/makers/internal/vote/domain/Vote.java
  src/main/java/org/sopt/makers/internal/vote/domain/VoteOption.java
  src/main/java/org/sopt/makers/internal/vote/domain/VoteSelection.java
  src/main/java/org/sopt/makers/internal/vote/dto/request/VoteRequest.java
  src/main/java/org/sopt/makers/internal/vote/dto/request/VoteSelectionRequest.java
  src/main/java/org/sopt/makers/internal/vote/dto/response/VoteOptionResponse.java
  src/main/java/org/sopt/makers/internal/vote/dto/response/VoteResponse.java
  src/main/java/org/sopt/makers/internal/vote/repository/VoteOptionRepository.java
  src/main/java/org/sopt/makers/internal/vote/repository/VoteQueryRepository.java
  src/main/java/org/sopt/makers/internal/vote/repository/VoteRepository.java
  src/main/java/org/sopt/makers/internal/vote/repository/VoteSelectionRepository.java
  src/main/java/org/sopt/makers/internal/vote/service/VoteService.java
  src/test/java/org/sopt/makers/internal/community/service/post/CommunityPostServiceTest.java
  src/test/java/org/sopt/makers/internal/service/community/CommunityServiceUnitTest.java
  src/test/java/org/sopt/makers/internal/service/community/category/CategoryServiceUnitTest.java
  src/test/java/org/sopt/makers/internal/vote/service/VoteServiceTest.java
Labels: size/XXL

#694 [Fix] 글 수정시에도 언급 푸시 알람 가도록 수정
  src/main/java/org/sopt/makers/internal/community/dto/request/PostUpdateRequest.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
Labels: ⛏ Fix, size/S

#695 RELEASE 2025-07-07 13:30:00
  src/main/java/org/sopt/makers/internal/community/dto/request/PostUpdateRequest.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
Labels: size/S

#698 RELEASE 2025-07-14 12:43:00
  src/main/java/org/sopt/makers/internal/community/controller/CommunityController.java
  src/main/java/org/sopt/makers/internal/community/dto/response/PopularPostResponse.java
  src/main/java/org/sopt/makers/internal/community/mapper/CommunityResponseMapper.java
  src/main/java/org/sopt/makers/internal/community/repository/CommunityQueryRepository.java
  src/main/java/org/sopt/makers/internal/community/repository/post/CommunityPostRepository.java
  src/main/java/org/sopt/makers/internal/community/service/category/CategoryRetriever.java
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
  src/main/java/org/sopt/makers/internal/internal/InternalOpenApiController.java
  src/main/java/org/sopt/makers/internal/internal/dto/InternalLatestPostResponse.java
  src/main/java/org/sopt/makers/internal/internal/dto/InternalPopularPostResponse.java
Labels: release, size/L, 주민🥭, 정교🥑

#701 [Fix] 상위 카테고리 조회 문제 해결
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
Labels: ⛏ Fix, size/XS, 정교🥑

#702 RELEASE 2025-07-17 08:57:00
  src/main/java/org/sopt/makers/internal/community/service/post/CommunityPostService.java
Labels: release, size/XS, 정교🥑

#707 [Feat] 타임캡솝 조회 로직 Sp4에 맞게 수정
  src/main/java/org/sopt/makers/internal/common/auth/jwtFilter/JwtAuthenticationFilter.java
  src/main/java/org/sopt/makers/internal/common/auth/jwtFilter/SecurityConfig.java
  src/main/java/org/sopt/makers/internal/resolution/controller/AdminController.java
  src/main/java/org/sopt/makers/internal/resolution/controller/UserResolutionController.java
  src/main/java/org/sopt/makers/internal/resolution/domain/UserResolutionLuckyPick.java
  src/main/java/org/sopt/makers/internal/resolution/dto/response/LuckyPickResponse.java
  src/main/java/org/sopt/makers/internal/resolution/dto/response/ResolutionResponse.java
  src/main/java/org/sopt/makers/internal/resolution/mapper/UserResolutionResponseMapper.java
  src/main/java/org/sopt/makers/internal/resolution/repository/UserResolutionLuckyPickRepository.java
  src/main/java/org/sopt/makers/internal/resolution/repository/UserResolutionRepository.java
  src/main/java/org/sopt/makers/internal/resolution/service/LuckyPickService.java
  src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionService.java
Labels: ✨Feature, size/L

#709 [fix] 단어게임 첫 게임인 경우 룸 조회 안되는 오류 수정
  src/main/java/org/sopt/makers/internal/wordchaingame/service/WordChainGameService.java
Labels: size/M

#711 [Fix] 댓글 조회 시 commentId 기반으로 조회되도록 수정
  src/main/java/org/sopt/makers/internal/community/repository/anonymous/AnonymousCommentProfileRepository.java
  src/main/java/org/sopt/makers/internal/community/service/CommunityCommentService.java
Labels: ⛏ Fix, size/XS, 정교🥑

#712 RELEASE 2025-07-26 09:15:00
  src/main/java/org/sopt/makers/internal/common/auth/jwtFilter/JwtAuthenticationFilter.java
  src/main/java/org/sopt/makers/internal/common/auth/jwtFilter/SecurityConfig.java
  src/main/java/org/sopt/makers/internal/resolution/controller/AdminController.java
  src/main/java/org/sopt/makers/internal/resolution/controller/UserResolutionController.java
  src/main/java/org/sopt/makers/internal/resolution/domain/UserResolutionLuckyPick.java
  src/main/java/org/sopt/makers/internal/resolution/dto/response/LuckyPickResponse.java
  src/main/java/org/sopt/makers/internal/resolution/dto/response/ResolutionResponse.java
  src/main/java/org/sopt/makers/internal/resolution/mapper/UserResolutionResponseMapper.java
  src/main/java/org/sopt/makers/internal/resolution/repository/UserResolutionLuckyPickRepository.java
  src/main/java/org/sopt/makers/internal/resolution/repository/UserResolutionRepository.java
  src/main/java/org/sopt/makers/internal/resolution/service/LuckyPickService.java
  src/main/java/org/sopt/makers/internal/resolution/service/UserResolutionService.java
Labels: size/L
